version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: h4ad_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_HOST: "localhost"
    ports:
      - ${DB_PORT}:3306
    networks:
      - backend

  web:
    image: nginx:latest
    container_name: h4ad_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/h5bp:/etc/nginx/h5bp
    networks:
      - backend
    depends_on:
      - api

  api:
    image: h4ad/api
    env_file:
      - .env
    container_name: h4ad_api
    volumes:
      - ${SQLITE_DATABASE_HOST_PATH}:${SQLITE_DATABASE_DOCKER_PATH}
    environment:
      - NODE_ENV=production
      - DB_TYPE=${DB_TYPE}
      - DB_DATABASE=${DB_DATABASE}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - DB_MIGRATIONS_RUN=${DB_MIGRATIONS_RUN}
      - API_DEFAULT_STRATEGY=${API_DEFAULT_STRATEGY}
      - API_BASE_PATH=${API_BASE_PATH}
      - API_PORT=${API_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - SWAGGER_TITLE=${SWAGGER_TITLE}
      - SWAGGER_DESCRIPTION=${SWAGGER_DESCRIPTION}
      - SWAGGER_VERSION=${SWAGGER_VERSION}
      - SWAGGER_TAG=${SWAGGER_TAG}
    networks:
      - backend

networks:
  backend:
